# Use an official MongoDB image as the base image
FROM mongo:latest

# Copy the initialization script to the container
COPY ./data/init-mongo.js /docker-entrypoint-initdb.d/

# Expose MongoDB default port
EXPOSE 27017
